### ISSUE TITLE
sdist doesnt include tests

### ISSUE THREAD

**Issue by jayvdb** [ssato/python-anytemplate#7]
Hi @ssato. 

openSUSE packaging ongoing at https://build.opensuse.org/package/show/home:jayvdb:moban/python-anytemplate

pypi v0.5.0 sdist doesnt include tests.

Also https://github.com/ssato/python-anytemplate/releases/tag/RELEASE_0.1.4 is the latest tag.

On `next`, `python2 setup.py test` doesnt run any tests, and `python{2,3} -m nose` doesnt run any tests.

Some of the tests do `PYTHONPATH=. python...` when they should use `sys.executable`

Unrelated, python-anyconfig-{configobj,cbor2,pyjavaproperties}-backend isnt on pypi yet.

Also would you mind removing `tox-travis` from setup.py test requirements from the backends, as it is a tox & travis only test requirement, not a generic packaging requirement.

And none of the backends have any tests in the sdist either, making the test requirements especially interesting ;-)

**Comment by ssato** [comment]
Thanks a lot for your report! I think that I resolved the original issue by the commit 9ad4a6d.

About other problems not look related directly to this issue you mentioned here, could you please open another issues for each corresponding projects?

**Comment by jayvdb** [comment]
No, the same problems occur throughout the collection.  It isnt worth my time to raise lots of little bugs in each repo about all of them.  You would encounter exactly the same problems if packaging them all.  Ideally you have scripts & templates to keep them all in sync. ;-)

**Comment by ssato** [comment]
Then,  it's not also worth my personal time to work for your issue reporting jumbling of problems.
(These are my personal projects and it's not my day job to develop something.)

Have a nice day.
